### ISSUE TITLE
Template is not building 

### ISSUE THREAD

**Issue by kajedot** [web3templates/nextly-template#7]
Hello. Unfortunately your example template is not building locally via npn run build, nor with vercel. It's pure cloned example - I didn't changed anything.

local:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/22113075/204326900-767b1111-c60f-41a9-9274-7ef00cd56fa2.png">

vercel:

> [17:07:46.780] Cloning github.com/kajedot/nextly-template1 (Branch: main, Commit: 3d0d770)
[17:07:47.014] Previous build cache not available
[17:07:47.360] Cloning completed: 579.871ms
[17:07:47.850] Running "vercel build"
[17:07:48.333] Vercel CLI 28.5.6
[17:07:48.634] Installing dependencies...
[17:07:48.992] yarn install v1.22.17
[17:07:49.058] [1/4] Resolving packages...
[17:07:49.200] [2/4] Fetching packages...
[17:07:54.178] [3/4] Linking dependencies...
[17:07:54.179] warning " > @emotion/babel-plugin@11.3.0" has unmet peer dependency "@babel/core@^7.0.0".
[17:07:54.179] warning "@emotion/css > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
[17:07:57.760] [4/4] Building fresh packages...
[17:07:57.775] Done in 8.79s.
[17:07:57.816] Detected Next.js version: 11.1.0
[17:07:57.818] Running "yarn run build"
[17:07:58.081] yarn run v1.22.17
[17:07:58.122] $ next build
[17:07:58.857] info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
[17:07:58.986] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[17:07:58.987] This information is used to shape Next.js' roadmap and prioritize features.
[17:07:58.987] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[17:07:58.987] https://nextjs.org/telemetry
[17:07:58.987] 
[17:07:59.048] info  - Checking validity of types...
[17:07:59.187] warn  - No ESLint configuration detected. Run next lint to begin setup
[17:07:59.188] info  - Creating an optimized production build...
[17:07:59.378] Browserslist: caniuse-lite is outdated. Please run:
[17:07:59.378] npx browserslist@latest --update-db
[17:07:59.378] 
[17:07:59.379] Why you should do it regularly:
[17:07:59.379] https://github.com/browserslist/browserslist#browsers-data-updating
[17:07:59.551]   this[kHandle] = new _Hash(algorithm, xofLen);
[17:07:59.551]                   ^
[17:07:59.551] 
[17:07:59.552] Error: error:0308010C:digital envelope routines::unsupported
[17:07:59.552]     at new Hash (node:internal/crypto/hash:71:19)
[17:07:59.552]     at Object.createHash (node:crypto:133:10)
[17:07:59.552]     at BulkUpdateDecorator.hashFactory (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:138458:18)
[17:07:59.552]     at BulkUpdateDecorator.update (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:138359:50)
[17:07:59.552]     at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:59115:9
[17:07:59.552]     at processTicksAndRejections (node:internal/process/task_queues:82:21)
[17:07:59.552]     at runNextTicks (node:internal/process/task_queues:64:3)
[17:07:59.553]     at process.processImmediate (node:internal/timers:442:9) {
[17:07:59.553]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[17:07:59.553]   library: 'digital envelope routines',
[17:07:59.553]   reason: 'unsupported',
[17:07:59.553]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[17:07:59.553] }
[17:07:59.553] 
[17:07:59.553] Node.js v18.12.1
[17:07:59.571] error Command failed with exit code 1.
[17:07:59.572] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[17:07:59.592] Error: Command "yarn run build" exited with 1

**Comment by syno3** [comment]
am experiencing the same issue is there a solution ?

**Comment by ZeroQ4** [comment]
add to package.json

```
"engines": {
  "node": "16.x"
},
```

**Comment by surjithctly** [comment]
Closed in favor of new updates. Please open a new issue if still exists.
